# Generated by Django 5.2.4 on 2025-07-22 14:02

import django.utils.timezone
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название документа"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=documents.models.Document.get_upload_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("signature", "На подпись"),
                            ("general", "Общий"),
                            ("review", "Для ознакомления"),
                            ("private", "Приватный"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Подтвержден"),
                            ("rejected", "Отклонен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
