# Generated by Django 5.2.4 on 2025-07-22 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователи с доступом",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
